<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('documents')->insert([
            [
                'judul' => 'Dokumen 1',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Draft',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 1,
                'user_id' => 6,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 2',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'On Process',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 3,
                'user_id' => 8,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 3',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Revision by AMO Region',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 2,
                'user_id' => 7,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 4',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Revision by MO',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 4,
                'user_id' => 9,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 5',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Revision by CCH',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 4,
                'user_id' => 9,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 6',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Accept by AMO Region',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 3,
                'user_id' => 8,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 7',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Accept by MO',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 1,
                'user_id' => 6,
                'category_id' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Dokumen 8',
                'periode_mulai' => '2026-01-04',
                'periode_selesai' => '2026-12-31',
                'status' => 'Accept by CCH',
                'file_name' => 'program_cicilan_amskin.docx',
                'file_path' => 'documents/program_cicilan_amskin.docx',
                'file_size' => 204800,
                'file_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'area_id' => 2,
                'user_id' => 7,
                'category_id' => 11,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}